class NotFoundException(Exception): ...


class InvalidStorageFormatException(Exception): ...


class RequestValidationException(Exception): ...


class InvalidDraftVersionException(Exception): ...


class AuthError(Exception): ...


class InternalServerError(Exception): ...


class JobExistsException(Exception): ...


class JobAlreadyCompleteException(Exception): ...


class NoSuchImportableDataset(Exception): ...


class BadQueryException(Exception): ...


class BumpingDisabledException(Exception): ...


class NameValidationError(Exception): ...


class DatastoreNotFoundException(Exception): ...
