class DataNotFoundException(Exception): ...


class InvalidStorageFormatException(Exception): ...


class RequestValidationException(Exception): ...


class InvalidDraftVersionException(Exception): ...


class AuthError(Exception): ...


class InternalServerError(Exception): ...
